name:       smsn-models
version:    0.1.0

extra-source-files:
  - stack.yaml

dependencies:
  - base
  - containers
#  - hydra

  # Hydra dependencies
  - HsYAML                        >= 0.2.1 && < 0.3
  - aeson                         >= 2.0.0 && < 2.2
  - aeson-pretty                  >= 0.8.9 && < 0.9
  - base                          >= 4.16.3 && < 4.17
  - bytestring                    >= 0.11.3 && < 0.12
  - containers                    >= 0.6.5 && < 0.7
  - directory                     >= 1.3.6 && < 1.4
  - filepath                      >= 1.4.2 && < 1.5
  - scientific                    >= 0.3.7 && < 0.4
  - split                         >= 0.2.3 && < 0.3
  - text                          >= 1.2.5 && < 1.3
  - unordered-containers          >= 0.2.19 && < 0.3
  - vector                        >= 0.12.0 && < 0.14

library:
  source-dirs:
    - src/main/haskell
    - src/gen-main/haskell
    - hydra/hydra-haskell/src/main/haskell
    - hydra/hydra-haskell/src/gen-main/haskell

tests:
  smsn-models-test:
    main: Spec.hs
    source-dirs: src/test/haskell
    dependencies:
#      - hydra
      - hspec
      - hspec-discover
      - HUnit
      - QuickCheck
